version: "3.3"

services:
  ################################################
  ####        Traefik Proxy Setup           #####
  ###############################################
  traefik:
    image: traefik:2.2
    restart: unless-stopped
    container_name: traefik
    ports:
      - "80:80" # <== http
      - "8080:8080" # <== :8080 is where the dashboard runs on
      - "443:443" # <== https
      # - "3306:3306" # <== mariadb/mysql
      # - 5432:5432 # <== postgresql
    command:
    #### These are the CLI commands that will configure Traefik and tell it how to work! ####
      ## API Settings - https://docs.traefik.io/operations/api/, endpoints - https://docs.traefik.io/operations/api/#endpoints ##
      # - --api.insecure=false # <== Enabling insecure api, NOT RECOMMENDED FOR PRODUCTION
      - --api.dashboard=true # <== Enabling the dashboard to view services, middlewares, routers, etc...
      - --api.debug=true # <== Enabling additional endpoints for debugging and profiling
      ## Log Settings (options: ERROR, DEBUG, PANIC, FATAL, WARN, INFO) - https://docs.traefik.io/observability/logs/ ##
      - --log.level=DEBUG # <== Setting the level of the logs from traefik
      ## Provider Settings - https://docs.traefik.io/providers/docker/#provider-configuration ##
      - --providers.docker=true # <== Enabling docker as the provider for traefik
      - --providers.docker.exposedbydefault=false # <== Don't expose every container to traefik, only expose enabled ones
      - --providers.file.filename=/dynamic.yaml # <== Referring to a dynamic configuration file
      - --providers.docker.network=proxy # <== Operate on the docker network named proxy

      ## Entrypoints Settings
      # Web related stuff 
      - --entrypoints.web.address=:80 # <== Defining an entrypoint for port :80 named web
      - --entrypoints.web-secured.address=:443 # <== Defining an entrypoint for https on port :443 named web-secured
      # Databases
      # - --entrypoints.mariadb.address=:3306 # mariadb
      # - --entrypoints.postgres.address=:5432 # postgres

      ## Certificate Settings (Let's Encrypt) -  https://docs.traefik.io/https/acme/#configuration-examples ##
      - --certificatesresolvers.le.acme.tlschallenge=true # <== Enable TLS-ALPN-01 to generate and renew ACME certs
      - --certificatesresolvers.le.acme.email=adrianvillanueva997@gmail.com # <== Setting email for certs
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json # <== Defining acme file to store cert information
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
    volumes:
      - ./letsencrypt:/letsencrypt # <== Volume for certs (TLS)
      - /var/run/docker.sock:/var/run/docker.sock # <== Volume for docker admin
      - ./dynamic.yml:/dynamic.yml # <== Volume for dynamic conf file, **ref: line 27
    networks:
      - proxy # <== Placing traefik on the network named web, to access containers on this network
    labels:
    #### Labels define the behavior and rules of the traefik proxy for this container ####
    - "traefik.enable=true" # <== Enable traefik on itself to view dashboard and assign subdomain to view it
    - "traefik.http.routers.api.rule=Host(`traefik.thexiao77.xyz`)" # <== Setting the domain for the dashboard
    - "traefik.http.routers.api.middlewares=traefik-https"
    - "traefik.http.middlewares.traefik-https.redirectscheme.scheme=https"
    - "traefik.http.middlewares.traefik-https.redirectscheme.permanent=true"
    - "traefik.http.routers.api.service=api@internal" # <== Enabling the api to be a service to access
    - "traefik.http.routers.api.middlewares=traefik-auth"
    - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:asdasdasd/"
    - traefik.http.routers.api.tls.certresolver=le
    - traefik.http.routers.api.tls=true
    - traefik.http.routers.api.entrypoints=web-secured
    - "traefik.docker.network=proxy"


networks: 
    proxy:
        external: true