version: "3.3"

services:
  ################################################
  ####        Traefik Proxy Setup           #####
  ###############################################
  traefik:
    image: traefik:2.4
    restart: unless-stopped
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80" # <== http
      - "8080:8080" # <== :8080 is where the dashboard runs on
      - "443:443" # <== https
      - "8082"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /home/xiao/docker/traefik/data/traefik.yml:/traefik.yml:ro
     - /home/xiao/docker/traefik/data/acme.json:/acme.json
     - /home/xiao/docker/traefik/data/config.yml:/config.yml:ro
    networks:
      - proxy # <== Placing traefik on the network named web, to access containers on this network
    labels:
    - traefik.enable=true # <== Enable traefik on itself to view dashboard and assign subdomain to view it
    - traefik.http.routers.traefik.entrypoints=http
    - traefik.http.routers.traefik.rule=Host(`yourdomain.com`)
    - traefik.http.middlewares.traefik-auth.basicauth.users=user:password
    - traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https
    - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
    - traefik.http.routers.traefik.middlewares=traefik-https-redirect
    - traefik.http.routers.traefik-secure.entrypoints=https
    - traefik.http.routers.traefik-secure.rule=Host(`yourdomain.com`)
    - traefik.http.routers.traefik-secure.middlewares=traefik-auth
    - traefik.http.routers.traefik-secure.tls=true
    - traefik.http.routers.traefik-secure.service=api@internal
    - traefik.http.routers.traefik-secure.tls.certresolver=le
    - traefik.docker.network=proxy"
    - com.centurylinklabs.watchtower.enable="true"

networks: 
    proxy:
        external: true
