version: '3'
services: 
    jekill_blog:
        container_name: jekyll_blog
        image: blog_jekill_blog
        build: .
        # command: bash -c "bundle && jekyll serve --watch --force_polling --verbose"
        # command: jekyll new . --force
        ports: 
            - 80:4000
        volumes: 
            - ./jekyll_blog:/srv/jekyll
        networks: 
            - proxy
        labels:
            - "traefik.enable=true"
            - "traefik.http.middlewares.jekyll-blog-redirect-websecure.redirectscheme.scheme=https"
            - "traefik.http.middlewares.jekyll-blog-redirect-websecure.redirectscheme.permanent=true"
            - "traefik.http.routers.jekyll-blog-web.middlewares=jekyll-blog-redirect-websecure"
            - traefik.http.routers.jekyll-blog-web.rule=Host(`blog.thexiao77.xyz`)
            - traefik.http.routers.jekyll-blog-web.entrypoints=web
            - traefik.http.routers.jekyll-blog-websecure.rule=Host(`blog.thexiao77.xyz`)
            - traefik.http.routers.jekyll-blog-websecure.tls.certresolver=le
            - traefik.http.routers.jekyll-blog-websecure.tls=true
            - "traefik.http.services.jekyll-blog-websecure.loadbalancer.server.port=4000"
            - traefik.http.routers.jekyll-blog-websecure.entrypoints=web-secured
            - "traefik.docker.network=proxy"
    
networks: 
    proxy:
        external: true

volumes: 
    jekyll_blog: